### ISSUE TITLE
BUG - ui5-middleware-fe-mockserver version 2.1.67 or high causes regression with ALP floorplan

### ISSUE THREAD

**Issue by quiggs1001** [SAP/open-ux-odata#541]
### Related Feature
Feature request: _issue number_

Please see the attached generated Fiori project.  Creating this project with an ALP floorplan and then using the `npm run start-local` command to start the project with mock data is failing to display.  Using v 2.1.65 or lower of this library ensures the data loads correctly.

### Steps to Reproduce
1. Unzip the attached project [project123-2023-04-181530.zip](https://github.com/SAP/open-ux-odata/files/11263588/project123-2023-04-181530.zip)
2. Run `npm i` to install the node modules
3. Start the application locally with mock data: `npm run start-local`.
4. Once the application is loaded, click on the `Go` button to load the data.

### Expected results

The ALP charts display as expected.

### Actual results

There is an error in the console and nothing is displayed.  If I downgrade the ui5-middleware-fe-mockserver version to 2.1.65 then it works successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/17096912/232827102-4d685364-5c76-4496-944d-7366fa4a059f.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Fixed in version 2.1.83

**Comment by sineadro** [comment]
@nlunets @quiggs1001 

Retested using the latest mockserver 2.1.83

````
npm run start-local

> project123@0.0.1 start-local
> fiori run --config ./ui5-local.yaml --open "test/flpSandbox.html?sap-ui-xx-viewCache=false#testcomsapproject123-tile"

info graph:helpers:ui5Framework Using SAPUI5 version: 1.102.0
warn graph:helpers:ui5Framework Dependency sap.fe.templates is restricted for use by SAP internal projects only! If the project test.com.sap.project123 is an SAP internal project, add the attribute "allowSapInternal: true" to its metadata configuration
info fiori-tools-proxy Starting fiori-tools-proxy using following configuration:
info fiori-tools-proxy proxy: 'undefined'
info fiori-tools-proxy ignoreCertError: 'false'
info fiori-tools-proxy backend: [{"path":"/sap","url":"https://sap-ux-mock-services-v4-alp.cfapps.us10.hana.ondemand.com"}]
info fiori-tools-proxy ui5: []
info fiori-tools-proxy debug: 'false'
info fiori-tools-appreload Livereload middleware started for port 35729 and path /Users/I325307/SAPDevelop/tools-suite/tmp/project123/webapp
info backend-proxy-middleware Backend proxy created for https://sap-ux-mock-services-v4-alp.cfapps.us10.hana.ondemand.com /sap
Server started
URL: http://localhost:8080
info backend-proxy-middleware /sap/bc/lrep/flex/data/test.com.sap.project123.Component?sap-language=en
error lbt:analyzer:LibraryJS Unexpected property 'customElements' or wrong type for 'customElements' in sap.ui.getCore().initLibrary call in '/resources/sap/ui/integration/library.js'
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.dt' defined in the manifest.json or .library file of project 'sap.ushell.plugins.rta-personalize'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.rta' defined in the manifest.json or .library file of project 'sap.ushell.plugins.rta-personalize'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.dt' defined in the manifest.json or .library file of project 'sap.ushell.plugins.rta'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.rta' defined in the manifest.json or .library file of project 'sap.ushell.plugins.rta'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.suite.ui.generic.template' defined in the manifest.json or .library file of project 'sap.ushell.plugins.ghostapp'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
info backend-proxy-middleware /sap/bc/lrep/flex/settings
info backend-proxy-middleware /sap/opu/odata/sap/ESH_SEARCH_SRV/ServerInfos?$expand=Services/Capabilities
info backend-proxy-middleware /sap/es/ina/GetServerInfo?_=1681985947065
MismatchedTokenException: Expecting token of type --> SimpleIdentifier <-- but found --> 'max' <--
    at ApplyParser.RecognizerEngine.consumeInternalError (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:475:31)
    at ApplyParser.RecognizerEngine.consumeInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:450:22)
    at ApplyParser.RecognizerApi.CONSUME3 (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:52:21)
    at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:249:38)
    at ApplyParser.RecognizerEngine.optionInternalLogic (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:212:27)
    at ApplyParser.RecognizerEngine.optionInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:190:21)
    at ApplyParser.RecognizerApi.OPTION2 (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:109:21)
    at ApplyParser.DEF (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:236:26)
    at ApplyParser.RecognizerEngine.manySepFirstInternalLogic (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:340:20)
    at ApplyParser.RecognizerEngine.manySepFirstInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:331:14)
    at ApplyParser.RecognizerApi.MANY_SEP (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:193:14)
    at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:230:18)
    at ApplyParser.invokeRuleWithTry (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
    at ApplyParser.wrappedGrammarRule [as aggregateTrafo] (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38)
    at ApplyParser.RecognizerEngine.subruleInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:422:37)
    at ApplyParser.RecognizerApi.SUBRULE (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:73:21)
    at ApplyParser.ALT (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:79:37)
    at ApplyParser.RecognizerEngine.orInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:400:42)
    at ApplyParser.RecognizerApi.OR (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:133:21)
    at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:76:18)
    at ApplyParser.invokeRuleWithTry (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
    at ApplyParser.wrappedGrammarRule [as applyTrafo] (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38) {
  token: {
    image: 'max',
    startOffset: 76,
    startLine: 1,
    startColumn: 77,
    tokenTypeIdx: 38,
    tokenType: {
      name: 'Aggregate Functions',
      PATTERN: /sum|min|max|countdistinct|average/,
      tokenTypeIdx: 38,
      CATEGORIES: [],
      categoryMatches: [],
      categoryMatchesMap: {},
      isParent: false
    }
  },
  resyncedTokens: [],
  previousToken: {
    image: ' ',
    startOffset: 75,
    startLine: 1,
    startColumn: 76,
    tokenTypeIdx: 23,
    tokenType: {
      name: 'Whitespace',
      PATTERN: /(\s|%20)+/,
      tokenTypeIdx: 23,
      CATEGORIES: [],
      categoryMatches: [],
      categoryMatchesMap: {},
      isParent: false
    }
  },
  context: {
    ruleStack: [
      'applyExpr',
      'applyTrafo',
      'groupbyTrafo',
      'applyExpr',
      'applyTrafo',
      'aggregateTrafo'
    ],
    ruleOccurrenceStack: [ 0, 2, 0, 0, 2, 0 ]
  }
} 0 [
  MismatchedTokenException: Expecting token of type --> SimpleIdentifier <-- but found --> 'max' <--
      at ApplyParser.RecognizerEngine.consumeInternalError (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:475:31)
      at ApplyParser.RecognizerEngine.consumeInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:450:22)
      at ApplyParser.RecognizerApi.CONSUME3 (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:52:21)
      at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:249:38)
      at ApplyParser.RecognizerEngine.optionInternalLogic (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:212:27)
      at ApplyParser.RecognizerEngine.optionInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:190:21)
      at ApplyParser.RecognizerApi.OPTION2 (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:109:21)
      at ApplyParser.DEF (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:236:26)
      at ApplyParser.RecognizerEngine.manySepFirstInternalLogic (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:340:20)
      at ApplyParser.RecognizerEngine.manySepFirstInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:331:14)
      at ApplyParser.RecognizerApi.MANY_SEP (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:193:14)
      at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:230:18)
      at ApplyParser.invokeRuleWithTry (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
      at ApplyParser.wrappedGrammarRule [as aggregateTrafo] (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38)
      at ApplyParser.RecognizerEngine.subruleInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:422:37)
      at ApplyParser.RecognizerApi.SUBRULE (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:73:21)
      at ApplyParser.ALT (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:79:37)
      at ApplyParser.RecognizerEngine.orInternal (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:400:42)
      at ApplyParser.RecognizerApi.OR (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:133:21)
      at ApplyParser.<anonymous> (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:76:18)
      at ApplyParser.invokeRuleWithTry (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
      at ApplyParser.wrappedGrammarRule [as applyTrafo] (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38) {
    token: {
      image: 'max',
      startOffset: 76,
      startLine: 1,
      startColumn: 77,
      tokenTypeIdx: 38,
      tokenType: [Object]
    },
    resyncedTokens: [],
    previousToken: {
      image: ' ',
      startOffset: 75,
      startLine: 1,
      startColumn: 76,
      tokenTypeIdx: 23,
      tokenType: [Object]
    },
    context: { ruleStack: [Array], ruleOccurrenceStack: [Array] }
  }
]
ERR! server:ux-fe-mockserver Error: Parsing errors detected
ERR! server:ux-fe-mockserver     at parseApply (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:458:15)
ERR! server:ux-fe-mockserver     at ODataRequest.parseParameters (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/odataRequest.js:47:61)
ERR! server:ux-fe-mockserver     at new ODataRequest (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/odataRequest.js:31:14)
ERR! server:ux-fe-mockserver     at handlePart (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/router/batchRouter.js:39:25)
ERR! server:ux-fe-mockserver     at /Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/router/batchRouter.js:85:44
ERR! server:ux-fe-mockserver     at runMicrotasks (<anonymous>)
ERR! server:ux-fe-mockserver     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR! server:ux-fe-mockserver  Error: Parsing errors detected
ERR! server:ux-fe-mockserver     at parseApply (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/applyParser.js:458:15)
ERR! server:ux-fe-mockserver     at ODataRequest.parseParameters (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/odataRequest.js:47:61)
ERR! server:ux-fe-mockserver     at new ODataRequest (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/request/odataRequest.js:31:14)
ERR! server:ux-fe-mockserver     at handlePart (/Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/router/batchRouter.js:39:25)
ERR! server:ux-fe-mockserver     at /Users/I325307/SAPDevelop/tools-suite/tmp/project123/node_modules/@sap-ux/fe-mockserver-core/dist/router/batchRouter.js:85:44
ERR! server:ux-fe-mockserver     at runMicrotasks (<anonymous>)
ERR! server:ux-fe-mockserver     at processTicksAndRejections (node:internal/process/task_queues:96:5)
````

I am still not seeing any chart with this version

**Comment by sineadro** [comment]
@nlunets @quiggs1001
After further review of the automated tests and the above screenshot, we cannot see any data in the table now although the chart data is display... 
As a result the automated test is still failing - Please investigate as to why the table data is not displaying now.

**Comment by nlunets** [comment]
@sineadro can you recheck ?

**Comment by nlunets** [comment]
I do ;)
